<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'lexik_paybox.request_handler' shared service.

include_once $this->targetDirs[3].'/vendor/lexik/paybox-bundle/Paybox/RequestInterface.php';
include_once $this->targetDirs[3].'/vendor/lexik/paybox-bundle/Paybox/AbstractRequest.php';
include_once $this->targetDirs[3].'/vendor/lexik/paybox-bundle/Paybox/System/Base/Request.php';

return $this->services['lexik_paybox.request_handler'] = new \Lexik\Bundle\PayboxBundle\Paybox\System\Base\Request($this->getParameter('lexik_paybox.parameters'), $this->parameters['lexik_paybox.servers'], ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')));
