<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXMbYMC2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXMbYMC2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXMbYMC2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXMbYMC2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXMbYMC2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XMbYMC2',
    'container.build_id' => '3d07a5a7',
    'container.build_time' => 1555074907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXMbYMC2');
